### ISSUE TITLE
Modal overlay remains after closing detail dialog 

### ISSUE THREAD

**Issue by sbley** [zeiss-digital-innovation/Saxonia-Campus-Angular#1]
Ich logge mich ein und klicke auf einen Slot. Danach klicke ich in den grauen Bereich neben dem Slot.
Erwartet: Der modale Dialog wird geschlossen und die Übersicht wird wieder angezeigt.
Tatsächlich: Das Dialogfenster wird zwar ausgeblendet. Der graue Bereich bleibt jedoch und ich kann aus diesem Zustand nur raus, indem ich mit F5 die Seite neu lade.

Gestetet mit Chrome 42, FF 38 und IE 10.

**Comment by sven-hoffmann** [comment]
Kann ich nicht reproduzieren :( Funktioniert bei mir in IE11, FF 37 und Chrome 43.

Eventuell hilft ein Redeploy und in den Advanced Einstellungen der Entwicklertools mal "Disable cache while dev tools open" in FF und Chrome zu aktivieren und zu refreshen?

**Comment by sbley** [comment]
Hat leider nicht geholfen.

Es ist sogar so, dass nach dem Einloggen schon der graue Overlay auf der Übersicht liegt. Mit F5 bekomme ich ihn weg. Wenn ich danach den Detaildialog öffne und wieder schließe, bleibt der graue Bereich da. Mit F5 geht's weg.

**Comment by sven-hoffmann** [comment]
Konnte es reproduzieren. angular-bootstrap ist noch inkompatibel mit angular 1.4.x, habe es nun in den dependencies fixiert auf angular 1.3.x in 5b9afff
Mach mal ein bower update + grunt clean + grunt serve und teste bitte mal bei dir.
