### ISSUE TITLE
Not all slots displayed in Firefox and IE

### ISSUE THREAD

**Issue by sbley** [zeiss-digital-innovation/Saxonia-Campus-Angular#2]
Ich nutze Firefox und logge mich ein.
Erwartet: Es werden alle Slots in einem Grid dargestellt.
Tatsächlich: Es werden nur vereinzelte Slots im Grid dargestellt.
![campus_ff](https://cloud.githubusercontent.com/assets/686538/7922470/afa92964-08ac-11e5-92cc-717cab098457.jpg)

**Comment by sven-hoffmann** [comment]
Fixed in 5d85520

**Comment by sbley** [comment]
Test ok
