### ISSUE TITLE
Hide seconds in time representations

### ISSUE THREAD

**Issue by sbley** [zeiss-digital-innovation/Saxonia-Campus-Angular#3]
Ist: Die Start- und Endzeiten der Slots werden im Format <Stunden>:<Minuten>:<Sekunden> angezeigt.
Soll: Die Start- und Endzeiten der Slots werden im Format <Stunden>:<Minuten> angezeigt.

**Comment by sven-hoffmann** [comment]
Fixed in 5d85520

**Comment by sbley** [comment]
Ok in Übersicht. Bitte auch in Detaildialog.

**Comment by sven-hoffmann** [comment]
Stimmt, danke, das war mir durch die Lappen gegangen, ist in a68ace7
